### ISSUE TITLE
Write details story about features to develop in first version

### ISSUE THREAD

**Issue by erluxman** [erluxman/productive#10]
0. Ability to link user's authentication code to app user code, this way when the user deletes the account accidentally, we can recover that user's data later and connect the user back to the old account

The amazing point from @Bipu  

> Let's not show the todos on the home page, rather let's show the social aspect of the app so that we can be motivated by other's progress than be overwhelmed by our own lack of progress. 

### Todos with reward

1. Todos need points to create and give rewards when done or reduce points if the user fails to tick them off before deadline time.

2. The points gathered by completing a todo is accumulated to user's points ( we will have a list of the day with daily rewards in case the user has less than the points needed to create two todos)

3. If the user has at least 5 points then the user doesn't get the grace points the user will get every day in order to be able to kick start  but if the user doesn't have sufficient points (let's say 5) at a start of the day, then we will borrow points from that day (we will keep a record of the  points gathered on that day) and provided it to users

4. Show user's completion streaks on top of an app like a circular progress bar that shows the number of todos done out of all todos./ total points gained out of total possible that day.

5. If the user fails to check the todo off then the invested points will be lost. if the user checks off the point late than the deadline, he will only get one point out of 3 (it's like points in football game 3,1,0) (2 points to create. a task).

6. Give some mechanism for the user to audit their to-do and habits in previous days but no dashboard material. (it's not that important) 

### Routine with Rewards

1. Just like Todo but it takes 10 points to create one and the name can't be edited after 1 hour of creation. (Points work exactly  todo, 3,1(Within 2 hours),0 points)

2. A habit will automatically be suspended if user fails to maintain streak for 3 days (3 times the duration ) i.e. 3 weeks if it was supposed to be done in once a week, in one week if it was supposed to be done 3 times a week, in 3 days if its a daily habit. user will need to pay half the points of it creation value (5 if first habit, 20 if second) to revive it.

3. Cannot create the second routine until the 14th streak of the first routine is completed  & user needs 40 points at least to create a second routine and 80 for the third, and 120 for the 4th. 

3. Common Routines (Global routines) to choose from and we will sort users with respect to the streak of that particular habit. And compare users with each other based on those routines. In addition to that, the habit will have details about how to form that habit, how other users were able to build that habit, kind of community.  (Habit, details, forum, leader board, guides, etc). May be user might even need to pass some tests (from the content of habit building docs to be able to subscribe to that habit)

### User's stats

1.  Todo streak 
2. Habit streak
3. Total points gained all time
4. Total todos finished in  week/month/year/all time
5. Total todos missed
6. Total todos that were checked after the deadline. 
7.  User's done distribution with respect to the day of the week.

### Leaderboard

1. Weekly, monthly, and Yearly overall leaderboard.

2.  Leaderboard on particular habits.

3. Also provide users which % they fall into like in StackOverflow.  

### Motivation Meter of user

1. Compute motivation of how consistent and motivated the user is in the current situation and Also might contribute to allowing the user to create todo or routine.  (i.e. user can trade motivation for  coins) 

2. Display user's motivation in their profile and around their avatar.  

### Social Feed 🏚

1.  If any user checks off any todo or routine, for now, that is added to the app's public timeline.

2.  When a user creates a routine, it's on a timeline.

3. When the user reached the 14th day. 21st day, 30 days, 72 day, 100 days then it is added to timeline. 

4.  Along with adding that to the timeline, users will also be rewarded for these milestones on particular habits, the same point as the milestone day count. simple. 

5.  User can cancel/(just post that he completed some task/routine without its name)  to post any such habit creation, milestone rewards, checking off a todo.

6. User will be able to look at other user's profiles and stats. If the user has chosen to share it. 

7. The social feed will only display stuff of the last 24 hours or last 1 week and not more than that.  and we will use firebase functions to fetch the timeline and put data into it. 

8. Other users can like and comment and share the user's posts on (their timeline, story or to other social media as images)

9. User's like (we will call encourage) will also add to the user's motivation. And we will take a natural log
     That means if the user gets 2.7 (3)  like then user will gain 1% percentage motivation, to next next percent motivation from same account user will need to have 7 likes,  for next motivation percentage user will need 20 likes,

basically increase in motivational percentage = ln(likes)

We can count the number of likes and comments for this motivation computation.

To get 100 % motivation just from likes, the user will need around 2.6*10^43 which is such a huge number, which means, the user will be able to get more motivation as he completes or tries to be more productive with his actions.

10. Send users notification when a user he is watching performs some actions or does some post or when some encourage or comments on your post. I think this is will be a huge push to start with.

11. Once the user reaches a streak of 100 days in three or more streak/habits he will be able to apply for a verified account and he will have to maintain consistency of about 80% motivation to maintain that badge.

   ##### Varities of social cards
 

- [x] User completed a todo
- [x] User checked off a habit
- [x] User reached a milestone
- [x] User failed to continue habit 
- [x] User removed a habit
- [x] User's motivation reached certain level (50%, 75%, 80%, 90%, 95%,100%)
- [x] User reached to top certain %. 
- [x] User was late to check off certain habit
- [x] User missed certain habit/task
